# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\kurir_main.ui'
#
# Created: Sun Jan 03 19:35:46 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(495, 374)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/kurir/email_go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditSubject = QtGui.QLineEdit(self.tab)
        self.lineEditSubject.setProperty("is_required", True)
        self.lineEditSubject.setObjectName("lineEditSubject")
        self.gridLayout.addWidget(self.lineEditSubject, 2, 1, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.comboBoxFrom = QtGui.QComboBox(self.tab)
        self.comboBoxFrom.setProperty("is_required", True)
        self.comboBoxFrom.setObjectName("comboBoxFrom")
        self.gridLayout.addWidget(self.comboBoxFrom, 0, 1, 1, 2)
        self.lineEditTo = QtGui.QLineEdit(self.tab)
        self.lineEditTo.setProperty("is_required", True)
        self.lineEditTo.setProperty("is_email", True)
        self.lineEditTo.setObjectName("lineEditTo")
        self.gridLayout.addWidget(self.lineEditTo, 1, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.plainTextEditBody = QtGui.QPlainTextEdit(self.tab)
        self.plainTextEditBody.setObjectName("plainTextEditBody")
        self.verticalLayout.addWidget(self.plainTextEditBody)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/kurir/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButtonAddFolder = QtGui.QToolButton(self.tab_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/kurir/folder_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAddFolder.setIcon(icon2)
        self.toolButtonAddFolder.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonAddFolder.setAutoRaise(True)
        self.toolButtonAddFolder.setObjectName("toolButtonAddFolder")
        self.horizontalLayout_2.addWidget(self.toolButtonAddFolder)
        self.toolButtonAddFiles = QtGui.QToolButton(self.tab_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/kurir/page_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAddFiles.setIcon(icon3)
        self.toolButtonAddFiles.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonAddFiles.setAutoRaise(True)
        self.toolButtonAddFiles.setObjectName("toolButtonAddFiles")
        self.horizontalLayout_2.addWidget(self.toolButtonAddFiles)
        self.toolButtonRemoveFiles = QtGui.QToolButton(self.tab_2)
        self.toolButtonRemoveFiles.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/kurir/page_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonRemoveFiles.setIcon(icon4)
        self.toolButtonRemoveFiles.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButtonRemoveFiles.setAutoRaise(True)
        self.toolButtonRemoveFiles.setObjectName("toolButtonRemoveFiles")
        self.horizontalLayout_2.addWidget(self.toolButtonRemoveFiles)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.treeWidgetFiles = QtGui.QTreeWidget(self.tab_2)
        self.treeWidgetFiles.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidgetFiles.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeWidgetFiles.setRootIsDecorated(False)
        self.treeWidgetFiles.setItemsExpandable(False)
        self.treeWidgetFiles.setObjectName("treeWidgetFiles")
        self.treeWidgetFiles.header().setDefaultSectionSize(80)
        self.verticalLayout_2.addWidget(self.treeWidgetFiles)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/kurir/attach.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon5, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSend = QtGui.QAction(MainWindow)
        self.actionSend.setIcon(icon)
        self.actionSend.setObjectName("actionSend")
        self.actionAccounts = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/kurir/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAccounts.setIcon(icon6)
        self.actionAccounts.setObjectName("actionAccounts")
        self.actionSettings = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/kurir/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon7)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/kurir/door_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon8)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addAction(self.actionSend)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAccounts)
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.comboBoxFrom)
        MainWindow.setTabOrder(self.comboBoxFrom, self.lineEditTo)
        MainWindow.setTabOrder(self.lineEditTo, self.lineEditSubject)
        MainWindow.setTabOrder(self.lineEditSubject, self.plainTextEditBody)
        MainWindow.setTabOrder(self.plainTextEditBody, self.toolButtonAddFolder)
        MainWindow.setTabOrder(self.toolButtonAddFolder, self.toolButtonAddFiles)
        MainWindow.setTabOrder(self.toolButtonAddFiles, self.toolButtonRemoveFiles)
        MainWindow.setTabOrder(self.toolButtonRemoveFiles, self.treeWidgetFiles)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Kurir", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "From:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "To:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Subject:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSubject.setToolTip(QtGui.QApplication.translate("MainWindow", "Subject", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSubject.setText(QtGui.QApplication.translate("MainWindow", "lalala", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFrom.setToolTip(QtGui.QApplication.translate("MainWindow", "From account", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditTo.setToolTip(QtGui.QApplication.translate("MainWindow", "To address", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditTo.setText(QtGui.QApplication.translate("MainWindow", "guyon.moree@gmail.com", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEditBody.setPlainText(QtGui.QApplication.translate("MainWindow", "w000t", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Message", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonAddFolder.setText(QtGui.QApplication.translate("MainWindow", "Add folder", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonAddFiles.setText(QtGui.QApplication.translate("MainWindow", "Add files", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonRemoveFiles.setText(QtGui.QApplication.translate("MainWindow", "Remove files", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetFiles.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "File name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetFiles.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Files (0)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSend.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSend.setToolTip(QtGui.QApplication.translate("MainWindow", "Send files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAccounts.setText(QtGui.QApplication.translate("MainWindow", "Accounts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAccounts.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage accounts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setToolTip(QtGui.QApplication.translate("MainWindow", "Exit kurir", None, QtGui.QApplication.UnicodeUTF8))

import kurir_rc
